import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { storage } from '../firebase';
import styles from '../styles/Home.module.css';
import { ref, uploadBytes, listAll, getDownloadURL } from 'firebase/storage';
import uuid from 'react-uuid';

export default function Home() {
	const [imageUpload, setImageUpload] = useState(null);
	const [imageList, setImageList] = useState([]);
	const [imageSrc, setImageSrc] = useState('');

	const imageListRef = ref(storage, 'product-images/');

	const uploadImage = () => {
		console.log(imageUpload);

		// store the file in the firebase storage
		if (imageUpload == null) return;

		// make image reference to identify which folder in storage we will store the image
		const imageRef = ref(
			storage,
			`product-images/${imageUpload.name + uuid()}`
		);

		uploadBytes(imageRef, imageUpload).then((snapshot) => {
			getDownloadURL(snapshot.ref).then((url) => {
				// todo,  add this to product image in your mighty jaxx product dashboard project
				console.log(url);
				setImageSrc(url);
				// setImageList((prev) => [...prev, url]);
			});
		});
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>NextJs Firebase Storage</h1>
				<br />
				<input
					type="file"
					onChange={(e) => setImageUpload(e.target.files[0])}
				/>
				<button onClick={uploadImage}>Upload Image</button>
				<br />
				{imageSrc && (
					<Image
						src={imageSrc}
						alt="productImg"
						width={500}
						height={500}
						loading="lazy"
					/>
				)}
			</main>
		</div>
	);
}
